CREATE TABLE MessierObjects (
    Number INTEGER PRIMARY KEY, 
    Messier TEXT, 
    NGC TEXT, 
    Name TEXT, 
    Type TEXT, 
    SubType TEXT, 
    Season TEXT, 
    Magnitude INTEGER, 
    Const TEXT, 
    ConstellationEnglish TEXT, 
    Constellation TEXT, 
    RA TEXT, 
    Dec TEXT, 
    Distance INTEGER, 
    Size TEXT, 
    Discoverer TEXT, 
    Year INTEGER, 
    Captured INTEGER,
    CapYear INTEGER,
    Remarks TXT
);
